site_name: MTS IOT Documentation

nav:
  - Home: README.md
  - Architecture: architecture.md
  - Changelog: CHANGELOG.md
  - Security: security.md
  - License: LICENSE.md
  - Android:
      - Architecture: android/android-architecture.md
      - Dependencies: android/android-dependencies.md
      - Setup: android/android-setup.md
      - Security: android/android-security.md
  - iOS:
      - Architecture: ios/ios-architecture.md
      - Dependencies: ios/ios-dependencies.md
      - Setup: ios/ios-setup.md
      - Security: ios/ios-security.md
  - API MTS:
      - API Overview: api/mtsapi-overview.md
      - Authentication: api/mtsapi-auth.md
      - Endpoints: api/mtsapi-endpoints.md

theme: readthedocs
